version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - java-backend
      - python-backend
    networks:
      - app-network

  java-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  python-backend:
    build:
      context: ./backend/python-backend
      dockerfile: Dockerfile
    ports:
      - "5005:5005"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
